# LAB 4 - Storage Benchmark

### Step 1: Installations, Importing and Setting up the environment

### Step 1a: Importing the Libraries

In [ ]:
# !pip install kagglehub -q

import pandas as pd
import kagglehub
import os
from sqlalchemy import create_engine
import time
from sqlalchemy import text
import duckdb

### Step 1b: Installing and start PostgreSQL in Colab

In [ ]:
!apt-get -y install postgresql > /dev/null 2>&1
!service postgresql start

# Set a password for the default 'postgres' user and create a database for the lab
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'labpass';"
!sudo -u postgres psql -c "CREATE DATABASE lab4;"

 * Starting PostgreSQL 14 database server
   ...done.
ALTER ROLE
ERROR:  database "lab4" already exists

### Step 1c: Installing the Python driver so pandas/Python can talk to Postgres

In [ ]:
# Installing the Python-to-PostgreSQL driver
!pip install psycopg2-binary sqlalchemy -q

### Step 2: Loading the CSV, then create Postgres table and Parquet file

### Step 2a: Reading the CSV and Confirm it looks right

In [ ]:
# Download latest version of the dataset
path = kagglehub.dataset_download("prasad22/healthcare-dataset")
print("Path to dataset files:", path)

# List files in the downloaded dataset folder
print(os.listdir(path))
df = pd.read_csv(os.path.join(path, "healthcare_dataset.csv"))

print(df.shape)
print(df.dtypes)
df.head()

Downloading to /root/.cache/kagglehub/datasets/prasad22/healthcare-dataset/2.archive...

100%|██████████| 2.91M/2.91M [00:00<00:00, 100MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/prasad22/healthcare-dataset/versions/2
['healthcare_dataset.csv']

(55500, 15)
Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

### Step 3: Now push this same df into both Postgres and Parquet

### Step 3a: Write to Postgres

In [ ]:
# Connection string: postgresql://user:password@host:port/database
engine = create_engine('postgresql://postgres:labpass@localhost:5432/lab4')

df.to_sql('admissions', engine, if_exists='replace', index=False)
print("Loaded into Postgres.")

Loaded into Postgres.

### Step 3b: Write to Parquet

In [ ]:
df.to_parquet('admissions.parquet', index=False)
print("Saved as Parquet.")

# Quick size comparison
import os
csv_size = os.path.getsize(os.path.join(path, "healthcare_dataset.csv"))
parquet_size = os.path.getsize('admissions.parquet')
print(f"CSV size: {csv_size/1024:.1f} KB")
print(f"Parquet size: {parquet_size/1024:.1f} KB")

Saved as Parquet.
CSV size: 8202.4 KB
Parquet size: 2755.6 KB

### Step 4: Runing the benchmark query three ways, with timing

### Step 4a: CSV + pandas

In [ ]:
start = time.time()
result_pandas = df.groupby('Medical Condition')['Billing Amount'].agg(['mean', 'count']).sort_values('mean', ascending=False)
elapsed_pandas = time.time() - start

print(f"pandas time: {elapsed_pandas:.4f} seconds")
result_pandas

pandas time: 0.0192 seconds

                           mean  count
Medical Condition
Obesity            25805.971259   9231
Diabetes           25638.405577   9304
Asthma             25635.249359   9185
Arthritis          25497.327056   9308
Hypertension       25497.095761   9245
Cancer             25161.792707   9227

### Step 4b: Same query - Now against PostgreSQL

In [ ]:
start = time.time()
query = """
SELECT "Medical Condition", AVG("Billing Amount") AS mean, COUNT(*) AS count
FROM admissions
GROUP BY "Medical Condition"
ORDER BY mean DESC;
"""
result_postgres = pd.read_sql(text(query), engine)
elapsed_postgres = time.time() - start

print(f"PostgreSQL time: {elapsed_postgres:.4f} seconds")
result_postgres

PostgreSQL time: 0.0277 seconds

  Medical Condition          mean  count
0           Obesity  25805.971259   9231
1          Diabetes  25638.405577   9304
2            Asthma  25635.249359   9185
3         Arthritis  25497.327056   9308
4      Hypertension  25497.095761   9245
5            Cancer  25161.792707   9227

### Step 4c: Final one - DuckDB + Parquet

In [ ]:
start = time.time()
result_duckdb = duckdb.sql("""
    SELECT "Medical Condition", AVG("Billing Amount") AS mean, COUNT(*) AS count
    FROM 'admissions.parquet'
    GROUP BY "Medical Condition"
    ORDER BY mean DESC;
""").df()
elapsed_duckdb = time.time() - start

print(f"DuckDB time: {elapsed_duckdb:.4f} seconds")
result_duckdb

DuckDB time: 0.2636 seconds

  Medical Condition          mean  count
0           Obesity  25805.971259   9231
1          Diabetes  25638.405577   9304
2            Asthma  25635.249359   9185
3         Arthritis  25497.327056   9308
4      Hypertension  25497.095761   9245
5            Cancer  25161.792707   9227

### Step 4d: Rerun DuckDB + Parquet (warm start, duckdb already imported)

In [ ]:
start = time.time()
result_duckdb_warm = duckdb.sql("""
    SELECT "Medical Condition", AVG("Billing Amount") AS mean, COUNT(*) AS count
    FROM 'admissions.parquet'
    GROUP BY "Medical Condition"
    ORDER BY mean DESC;
""").df()
elapsed_duckdb_warm = time.time() - start

print(f"DuckDB time (warm): {elapsed_duckdb_warm:.4f} seconds")
result_duckdb_warm

DuckDB time (warm): 0.0093 seconds

  Medical Condition          mean  count
0           Obesity  25805.971259   9231
1          Diabetes  25638.405577   9304
2            Asthma  25635.249359   9185
3         Arthritis  25497.327056   9308
4      Hypertension  25497.095761   9245
5            Cancer  25161.792707   9227

Possible Reasons for DuckDB + Parquet to take longer time in first Run
- Run 1 (cold): 0.2636s — engine loads + initializes + opens file + runs
query
- Run 2 (warm): 0.0093s — engine already loaded, file already touched → just runs the query

### Step 4e. Rerun pandas

In [ ]:
start = time.time()
result_pandas_warm = df.groupby('Medical Condition')['Billing Amount'].agg(['mean', 'count']).sort_values('mean', ascending=False)
elapsed_pandas_warm = time.time() - start
print(f"pandas time (rerun): {elapsed_pandas_warm:.4f} seconds")

pandas time (rerun): 0.0449 seconds

### Step 4f: Rerun PostgreSQL

In [ ]:
start = time.time()
result_postgres_warm = pd.read_sql(text(query), engine)
elapsed_postgres_warm = time.time() - start
print(f"PostgreSQL time (rerun): {elapsed_postgres_warm:.4f} seconds")

PostgreSQL time (rerun): 0.0297 seconds

- There is not much difference compared to the first run for both CSV + pandas and PostgreSQL, because they were already initialized earlier.